theme: jekyll-theme-slate
title: "ProgramFiction | Ram"
description: Repository is about my learnings.
avatar: ./logo.gif

social-network-links:
  email: "ramakrushna@live.com"
  facebook: "ram2mishra"
  github: "programfiction"
  twitter: "ram2mishra"
  youtube: "c/programfiction"
  linkedin: "iamramakrushna"
  medium: "programfiction"

extra_javascript: 
    gtag.js
google-site-verification: googlecbe8af599f7667a8.html

google_analytics: "G-M9GXHYXKZR"

g-tag: G-M9GXHYXKZR