theme: jekyll-theme-slate
title: "ProgramFiction | Ram"
author: "Ramakrushna Mishra"
description: Repository is about my learnings.
avatar: "./dev.gif"
social-network-links:
  email: "ramakrushna@live.com"
  facebook: "ram2mishra"
  github: "programfiction"
  twitter: "ram2mishra"
  youtube: "c/programfiction"
  linkedin: "iamramakrushna"
  medium: "programfiction"

#google_analytics: "G-P51R3J7ZY5"
