theme: jekyll-theme-slate
title: "ProgramFiction | Ram"
description: Repository is about my learnings.
avatar: ./logo.gif

social-network-links:
  email: "ramakrushna@live.com"
  facebook: "ram2mishra"
  github: "programfiction"
  twitter: "ram2mishra"
  youtube: "c/programfiction"
  linkedin: "iamramakrushna"
  medium: "programfiction"

google_analytics: "G-P51R3J7ZY5"

g-tag: G-P51R3J7ZY5